name: Push_To_DockerHub

on:
  push:
    branches: "main"
    
jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    defaults:
      run:
        working-directory: "/"

    steps:
      - name: checkout_repository
        uses: actions/checkout@v4

      - name: docker_login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: docker_build_and_push
        uses: docker/build-push-action@v5
        with:
          context: "./"
          push: true
          tags: auto_docker:latest
